import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { store } from "@/redux/store";
import Providers from "@/lib/Providers";
import Navbar from "@/components/ui/components/Shared/Navbar";
import Footer from "@/components/ui/components/Shared/Footer";
import { Toaster } from "@/components/ui/toaster";
const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body
          className={cn(
            " bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
